# -*- coding: utf-8 -*-
"""SimpleCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cyqpp1PKiZeyjWq-ud7Pnr5yLHuMLux7
"""

# Install necessary library for creating a GUI.
!pip install ipywidgets

from ipywidgets import VBox, HBox, Button, Text, Label
from IPython.display import display

class Calculator:
    def __init__(self):
        self.output_text = Text(description="Result:", disabled=True)
        self.input_text = Text(description="Input:", disabled=False)
        self.buttons = self._create_buttons()

        self.display = VBox([self.output_text, self.input_text, HBox(self.buttons[:4]), HBox(self.buttons[4:8]), HBox(self.buttons[8:12]), HBox(self.buttons[12:])])

        self.expression = ""

    def _create_buttons(self):
        button_labels = [
            '7', '8', '9', '/',
            '4', '5', '6', '*',
            '1', '2', '3', '-',
            '0', '.', '=', '+'
        ]
        buttons = []
        for label in button_labels:
            button = Button(description=label)
            button.on_click(self._on_button_click)
            buttons.append(button)
        return buttons

    def _on_button_click(self, b):
        if b.description == '=':
            try:
                # Use the self.expression accumulated from button clicks
                self.expression = str(eval(self.expression))
                self.output_text.value = self.expression
                self.input_text.value = ""
                # Reset expression after evaluation
                self.expression = ""
            except Exception as e:
                self.output_text.value = "Error"
                self.input_text.value = ""
                self.expression = ""
        else:
            self.expression += b.description
            self.input_text.value = self.expression

    def display_calculator(self):
        display(self.display)

# To use the calculator:
calculator = Calculator()
calculator.display_calculator()

# Removed the Tkinter code as it requires a graphical display which is not available
# in this environment and was causing the TclError.

